/*******************************************************************************
 * Copyright (c) 2017, 2026 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.watchdog;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.io.IOException;
import java.io.StringWriter;
import java.io.Writer;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.Future;

import org.eclipse.kura.core.testutil.TestUtil;
import org.eclipse.kura.linux.watchdog.WatchdogServiceOptions.WatchdogMode;
import org.eclipse.kura.watchdog.CriticalComponent;
import org.junit.Test;

public class WatchdogServiceImplTest {

    private static final String WATCHDOG_TEST_DEVICE = "target/watchdogTestDevice";

    private class WatchdogTestWriter extends StringWriter {

        private int lastLength = 0;

        @Override
        public synchronized void write(String str) {
            super.write(str);
            notify();
        }

        public synchronized boolean waitForData(int delayMs) {
            if (toString().length() == this.lastLength) {
                try {
                    this.wait(delayMs);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                }
            }
            final int currentLength = toString().length();
            final boolean result = currentLength != this.lastLength;
            this.lastLength = currentLength;
            return result;
        }
    }

    private class TestDirectWatchdogStrategy extends DirectWatchdogStrategy {

        private final Writer testWriter;

        public TestDirectWatchdogStrategy(Writer testWriter) {
            this.testWriter = testWriter;
        }

        @Override
        protected Writer getWatchdogDeviceWriter(String watchdogDevice) throws IOException {
            return this.testWriter;
        }

        @Override
        protected boolean isWatchdogDeviceAvailable(String watchdogDevice) {
            return true;
        }
    }

    public class TestWatchdogServiceImpl extends WatchdogServiceImpl {

        private final Writer testWriter;
        private volatile boolean hasCheckedCriticalComponents;

        public TestWatchdogServiceImpl(Writer testWriter) {
            this.testWriter = testWriter;
        }

        @Override
        protected WatchdogStrategy createWatchdogStrategy(WatchdogMode mode) {
            return new TestDirectWatchdogStrategy(this.testWriter);
        }

        @Override
        protected synchronized void checkCriticalComponents() {
            super.checkCriticalComponents();
            this.hasCheckedCriticalComponents = true;
            notify();
        }

        public synchronized boolean waitForCriticalComponentCheck(int delayMs) {
            if (!this.hasCheckedCriticalComponents) {
                try {
                    this.wait(delayMs);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                }
            }
            return this.hasCheckedCriticalComponents;
        }
    }

    @Test
    public void testActivateDeactivate() throws NoSuchFieldException, IOException, InterruptedException {
        final WatchdogTestWriter watchdogWriter = new WatchdogTestWriter();
        TestWatchdogServiceImpl svc = new TestWatchdogServiceImpl(watchdogWriter);

        Map<String, Object> properties = getProperties(true);
        svc.activate(properties);

        assertTrue(svc.waitForCriticalComponentCheck(10000));
        assertTrue(watchdogWriter.waitForData(10000));
        assertTrue(watchdogWriter.toString().contains("w"));

        assertNotNull(TestUtil.getFieldValue(svc, "pollExecutor"));

        Future<?> task = (Future<?>) TestUtil.getFieldValue(svc, "pollTask");
        assertNotNull(task);

        assertFalse(task.isCancelled());

        svc.deactivate();

        assertNull(TestUtil.getFieldValue(svc, "pollTask"));
        assertTrue(task.isCancelled());
        assertNull(TestUtil.getFieldValue(svc, "pollExecutor"));

        assertTrue(watchdogWriter.waitForData(10000));
        assertTrue(watchdogWriter.toString().endsWith("V"));
    }

    private Map<String, Object> getProperties(boolean enabled) {
        Map<String, Object> properties = new HashMap<>();
        properties.put("watchdogDevice", WATCHDOG_TEST_DEVICE);
        properties.put("rebootCauseFilePath", "target/watchdogTestCauses");
        properties.put("enabled", enabled);
        properties.put("watchdogMode", "direct");

        return properties;
    }

    @Test
    public void testDisabledStillRefreshesWatchdog() throws NoSuchFieldException, IOException, InterruptedException {
        final WatchdogTestWriter watchdogWriter = new WatchdogTestWriter();
        TestWatchdogServiceImpl svc = new TestWatchdogServiceImpl(watchdogWriter);

        Map<String, Object> properties = getProperties(false);

        svc.activate(properties);

        assertTrue(watchdogWriter.waitForData(10000));
        assertTrue(watchdogWriter.toString().contains("w"));

        assertNull(TestUtil.getFieldValue(svc, "timedOutOn"));

        svc.deactivate();

        assertTrue(watchdogWriter.waitForData(5000));
        assertTrue(watchdogWriter.toString().contains("V"));
    }

    @Test
    public void testDirectDisable() throws Throwable {
        final WatchdogTestWriter watchdogWriter = new WatchdogTestWriter();

        DirectWatchdogStrategy strategy = new TestDirectWatchdogStrategy(watchdogWriter);
        Map<String, Object> properties = new HashMap<>();
        properties.put("watchdogDevice", WATCHDOG_TEST_DEVICE);
        properties.put("rebootCauseFilePath", "target/watchdogTestCauses");
        properties.put("enabled", true);
        properties.put("watchdogMode", "direct");

        WatchdogServiceOptions options = new WatchdogServiceOptions(properties);
        strategy.activate(options);

        strategy.refresh();
        assertTrue(watchdogWriter.waitForData(10000));
        assertTrue(watchdogWriter.toString().contains("w"));

        strategy.disable();
        assertTrue(watchdogWriter.waitForData(10000));
        assertTrue(watchdogWriter.toString().contains("V"));
    }

    @Test
    public void testRegisterUnregisterGetCriticalComponent() throws NoSuchFieldException {
        WatchdogServiceImpl svc = new WatchdogServiceImpl();

        List<CriticalComponentRegistration> criticalComponentRegistrations = new CopyOnWriteArrayList<>();
        TestUtil.setFieldValue(svc, "criticalComponentRegistrations", criticalComponentRegistrations);

        CriticalComponent cc1 = new TestCC("1", 0);
        svc.registerCriticalComponent(cc1);

        List<CriticalComponent> components = svc.getCriticalComponents();
        assertEquals(1, components.size());

        assertEquals("1", components.get(0).getCriticalComponentName());
        assertEquals(0, components.get(0).getCriticalComponentTimeout());

        svc.registerCriticalComponent(cc1);

        components = svc.getCriticalComponents();
        assertEquals(1, components.size());

        CriticalComponent cc2 = new TestCC("1", 0);
        svc.registerCriticalComponent(cc2);

        components = svc.getCriticalComponents();
        assertEquals(2, components.size());

        assertEquals(criticalComponentRegistrations.size(), components.size());

        CriticalComponent cc3 = new TestCC("3", 1);
        svc.registerCriticalService(cc3);

        components = svc.getCriticalComponents();
        assertEquals(3, components.size());

        assertEquals(criticalComponentRegistrations.size(), components.size());

        assertEquals("1", components.get(0).getCriticalComponentName());
        assertEquals(0, components.get(0).getCriticalComponentTimeout());

        assertEquals("1", components.get(1).getCriticalComponentName());
        assertEquals(0, components.get(1).getCriticalComponentTimeout());

        assertEquals("3", components.get(2).getCriticalComponentName());
        assertEquals(1, components.get(2).getCriticalComponentTimeout());

        svc.registerCriticalComponent(cc1);

        components = svc.getCriticalComponents();
        assertEquals(3, components.size());

        svc.unregisterCriticalComponent(cc1);

        components = svc.getCriticalComponents();
        assertEquals(2, components.size());

        svc.registerCriticalComponent(cc1);

        components = svc.getCriticalComponents();
        assertEquals(3, components.size());

        svc.unregisterCriticalComponent(cc1);

        components = svc.getCriticalComponents();
        assertEquals(2, components.size());

        svc.unregisterCriticalService(cc3);

        components = svc.getCriticalComponents();
        assertEquals(1, components.size());

        assertEquals("1", components.get(0).getCriticalComponentName());
        assertEquals(0, components.get(0).getCriticalComponentTimeout());
    }

    @Test
    public void testCheckin() throws NoSuchFieldException {
        WatchdogServiceImpl svc = new WatchdogServiceImpl();

        List<CriticalComponentRegistration> criticalComponentRegistrations = new CopyOnWriteArrayList<>();
        TestUtil.setFieldValue(svc, "criticalComponentRegistrations", criticalComponentRegistrations);

        CriticalComponent cc1 = new TestCC("1", 1);
        svc.registerCriticalComponent(cc1);

        CriticalComponent cc2 = new TestCC("2", 2);
        svc.registerCriticalComponent(cc2);

        CriticalComponentRegistration cci2 = criticalComponentRegistrations.get(1);
        TestUtil.setFieldValue(cci2, "updated", 12345L);

        svc.checkin(cc2);

        assertTrue((long) TestUtil.getFieldValue(cci2, "updated") > 12345L);
        assertTrue((long) TestUtil.getFieldValue(cci2, "updated") <= System.nanoTime());
    }

    @Test
    public void testWatchdogServiceOptionsDefaults() {
        Map<String, Object> properties = new HashMap<>();
        WatchdogServiceOptions options = new WatchdogServiceOptions(properties);

        assertFalse(options.isEnabled());
        assertEquals(Integer.valueOf(10000), options.getPingInterval());
        assertEquals("/dev/watchdog", options.getWatchdogDevice());
        assertEquals("/opt/eclipse/kura/data/kura-reboot-cause", options.getRebootCauseFilePath());
        assertEquals(WatchdogMode.SYSTEMD, options.getWatchdogMode());
    }

    @Test
    public void testWatchdogServiceOptionsSystemdMode() {
        Map<String, Object> properties = new HashMap<>();
        properties.put("watchdogMode", "systemd");

        WatchdogServiceOptions options = new WatchdogServiceOptions(properties);
        assertEquals(WatchdogMode.SYSTEMD, options.getWatchdogMode());
    }

    @Test
    public void testWatchdogServiceOptionsDirectMode() {
        Map<String, Object> properties = new HashMap<>();
        properties.put("watchdogMode", "direct");

        WatchdogServiceOptions options = new WatchdogServiceOptions(properties);
        assertEquals(WatchdogMode.DIRECT, options.getWatchdogMode());
    }

    @Test
    public void testWatchdogServiceOptionsInvalidModeFallsBackToSystemd() {
        Map<String, Object> properties = new HashMap<>();
        properties.put("watchdogMode", "invalid");

        WatchdogServiceOptions options = new WatchdogServiceOptions(properties);
        assertEquals(WatchdogMode.SYSTEMD, options.getWatchdogMode());
    }

    @Test
    public void testSystemdWatchdogStrategyDegradedMode() throws Exception {
        SystemdWatchdogStrategy strategy = new SystemdWatchdogStrategy();

        strategy.activate(null);

        assertTrue(strategy.isDegraded());

        strategy.refresh();

        strategy.disable();

        assertEquals(0, strategy.getHardwareTimeout());
    }

    @Test
    public void testAutoFallbackSystemdToDirect() throws NoSuchFieldException, IOException, InterruptedException {
        final WatchdogTestWriter watchdogWriter = new WatchdogTestWriter();

        WatchdogServiceImpl svc = new WatchdogServiceImpl() {
            @Override
            protected WatchdogStrategy createWatchdogStrategy(WatchdogMode mode) {
                if (mode == WatchdogMode.DIRECT) {
                    return new TestDirectWatchdogStrategy(watchdogWriter);
                }
                return super.createWatchdogStrategy(mode);
            }
        };

        Map<String, Object> properties = getProperties(true);
        svc.activate(properties);

        Thread.sleep(500);

        assertTrue(watchdogWriter.waitForData(5000));
        assertTrue(watchdogWriter.toString().contains("w"));

        svc.deactivate();
    }

    @Test
    public void testWatchdogModeFromString() {
        assertEquals(WatchdogMode.DIRECT, WatchdogMode.fromString("direct"));
        assertEquals(WatchdogMode.SYSTEMD, WatchdogMode.fromString("systemd"));
        assertEquals(WatchdogMode.SYSTEMD, WatchdogMode.fromString("SYSTEMD"));
        assertEquals(WatchdogMode.SYSTEMD, WatchdogMode.fromString("invalid"));
        assertEquals(WatchdogMode.SYSTEMD, WatchdogMode.fromString(null));
    }
}

class TestCC implements CriticalComponent {

    private final String name;
    private final int timeout;

    public TestCC(String name, int timeout) {
        this.name = name;
        this.timeout = timeout;
    }

    @Override
    public String getCriticalComponentName() {
        return this.name;
    }

    @Override
    public int getCriticalComponentTimeout() {
        return this.timeout;
    }

}
