/*******************************************************************************
 * Copyright (c) 2025, 2026 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.watchdog;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DirectWatchdogStrategy implements WatchdogStrategy {

    private static final Logger logger = LoggerFactory.getLogger(DirectWatchdogStrategy.class);

    private static final String[] STOP_WATCHDOGD_COMMANDS = { "systemctl stop watchdog", "service watchdog stop",
            "/etc/init.d/watchdog stop", "/etc/init.d/watchdog.sh stop" };

    private Writer watchdogFileWriter;
    private WatchdogServiceOptions options;

    @Override
    public void activate(WatchdogServiceOptions options) throws IOException {
        this.options = options;
        String watchdogDevice = options.getWatchdogDevice();

        if (!isWatchdogDeviceAvailable(watchdogDevice)) {
            throw new IOException("Watchdog device '" + watchdogDevice + "' does not exist");
        }

        openWatchdog(watchdogDevice, true);
    }

    @Override
    public void refresh() {
        try {
            writeWatchdogDevice("w");
        } catch (IOException e) {
            logger.error("Failed to refresh watchdog device '{}'",
                    this.options != null ? this.options.getWatchdogDevice() : "unknown", e);
        }
    }

    @Override
    public void disable() {
        try {
            writeWatchdogDevice("V");
        } catch (IOException e) {
            logger.error("Failed to write magic character to watchdog device '{}'",
                    this.options != null ? this.options.getWatchdogDevice() : "unknown", e);
        }
        closeWatchdogFileWriter();
    }

    @Override
    public int getHardwareTimeout() {
        return 0;
    }

    void stopWatchdogd() {
        for (final String stopCommand : STOP_WATCHDOGD_COMMANDS) {
            try {
                runCommand(stopCommand);
                Thread.sleep(5000);
                return;
            } catch (Exception e) {
                logger.debug("Command failed: {}", stopCommand, e);
            }
        }
    }

    protected Writer getWatchdogDeviceWriter(String watchdogDevice) throws IOException {
        return new FileWriter(new File(watchdogDevice));
    }

    protected boolean isWatchdogDeviceAvailable(String watchdogDevice) {
        return new File(watchdogDevice).exists();
    }

    private void openWatchdog(final String watchdogDevice, final boolean tryStopWatchdogd) throws IOException {
        try {
            this.watchdogFileWriter = getWatchdogDeviceWriter(watchdogDevice);
        } catch (IOException e) {
            if (tryStopWatchdogd) {
                stopWatchdogd();
                openWatchdog(watchdogDevice, false);
            } else {
                throw e;
            }
        }
    }

    private synchronized void writeWatchdogDevice(String value) throws IOException {
        if (this.watchdogFileWriter != null) {
            this.watchdogFileWriter.write(value);
            this.watchdogFileWriter.flush();
        }
    }

    private void closeWatchdogFileWriter() {
        if (this.watchdogFileWriter != null) {
            try {
                this.watchdogFileWriter.close();
            } catch (IOException e) {
                logger.error("Failed to close watchdog device",
                        this.options != null ? this.options.getWatchdogDevice() : "unknown", e);
            }
            this.watchdogFileWriter = null;
        }
    }

    private void runCommand(String command) throws IOException, InterruptedException {
        Process proc = Runtime.getRuntime().exec(command);
        int exitCode = proc.waitFor();
        if (exitCode != 0) {
            throw new IOException("Command '" + command + "' failed with exit code " + exitCode);
        }
    }
}