/*******************************************************************************
 * Copyright (c) 2025, 2026 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.watchdog;

import java.io.IOException;
import java.net.StandardProtocolFamily;
import java.net.UnixDomainSocketAddress;
import java.nio.ByteBuffer;
import java.nio.channels.DatagramChannel;
import java.nio.charset.StandardCharsets;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SystemdWatchdogStrategy implements WatchdogStrategy {

    private static final Logger logger = LoggerFactory.getLogger(SystemdWatchdogStrategy.class);

    static final String NOTIFY_SOCKET_ENV = "NOTIFY_SOCKET";
    static final String WATCHDOG_USEC_ENV = "WATCHDOG_USEC";
    static final String WATCHDOG_PID_ENV = "WATCHDOG_PID";

    private DatagramChannel notifyChannel;
    private UnixDomainSocketAddress notifyAddress;
    private long watchdogUsec;
    private boolean degraded;

    @Override
    public void activate(WatchdogServiceOptions options) throws Exception {
        String notifySocketPath = System.getenv(NOTIFY_SOCKET_ENV);

        if (notifySocketPath == null || notifySocketPath.isEmpty()) {
            logger.warn(
                    "NOTIFY_SOCKET environment variable is not set. "
                            + "Running in degraded mode: systemd watchdog pings will not be sent. "
                            + "Ensure Kura is running as a systemd service with WatchdogSec= configured.");
            this.degraded = true;
            return;
        }

        String watchdogPidStr = System.getenv(WATCHDOG_PID_ENV);
        if (watchdogPidStr != null) {
            try {
                long expectedPid = Long.parseLong(watchdogPidStr);
                long currentPid = ProcessHandle.current().pid();
                if (expectedPid != currentPid) {
                    logger.debug(
                            "WATCHDOG_PID ({}) does not match current PID ({}). "
                                    + "This is expected for forking services. "
                                    + "The notify socket will still be used for watchdog pings.",
                            expectedPid, currentPid);
                }
            } catch (NumberFormatException e) {
                logger.debug("WATCHDOG_PID environment variable is not a valid number: '{}'. Ignoring.",
                        watchdogPidStr, e);
            }
        }

        String watchdogUsecStr = System.getenv(WATCHDOG_USEC_ENV);
        if (watchdogUsecStr != null) {
            try {
                this.watchdogUsec = Long.parseLong(watchdogUsecStr);
                logger.info("systemd watchdog timeout set to {} usec ({} msec)", this.watchdogUsec,
                        this.watchdogUsec / 1000);
            } catch (NumberFormatException e) {
                logger.warn("WATCHDOG_USEC environment variable is not a valid number: '{}'. "
                        + "Watchdog timeout will not be available.", watchdogUsecStr, e);
            }
        }

        String socketPath = notifySocketPath;
        if (socketPath.startsWith("@")) {
            socketPath = "\0" + socketPath.substring(1);
        }

        this.notifyAddress = UnixDomainSocketAddress.of(socketPath);
        this.notifyChannel = DatagramChannel.open(StandardProtocolFamily.UNIX);

        logger.info("Systemd watchdog strategy activated. NOTIFY_SOCKET={}", notifySocketPath);
        this.degraded = false;
    }

    @Override
    public void refresh() {
        if (this.degraded) {
            return;
        }
        sendNotify("WATCHDOG=1\n");
    }

    @Override
    public void disable() {
        if (this.degraded) {
            return;
        }
        sendNotify("STOPPING=1\n");
        closeChannel();
    }

    @Override
    public int getHardwareTimeout() {
        if (this.watchdogUsec > 0) {
            return (int) (this.watchdogUsec / 1000);
        }
        return 0;
    }

    @Override
    public void trigger() {
        sendNotify("WATCHDOG=trigger\n");
    }

    void notifyReady() {
        sendNotify("READY=1\n");
    }

    @Override
    public boolean isDegraded() {
        return this.degraded;
    }

    long getWatchdogUsec() {
        return this.watchdogUsec;
    }

    private void sendNotify(String message) {
        if (this.notifyChannel == null || !this.notifyChannel.isOpen()) {
            logger.warn("Cannot send notification: channel is not open");
            return;
        }

        try {
            ByteBuffer buffer = ByteBuffer.wrap(message.getBytes(StandardCharsets.UTF_8));
            this.notifyChannel.send(buffer, this.notifyAddress);
            logger.debug("Sent notification: {}", message.trim());
        } catch (IOException e) {
            logger.error("Failed to send notification to systemd: {}", message.trim(), e);
        }
    }

    private void closeChannel() {
        if (this.notifyChannel != null) {
            try {
                this.notifyChannel.close();
            } catch (IOException e) {
                logger.error("Failed to close notify channel", e);
            }
            this.notifyChannel = null;
        }
    }
}
