/*******************************************************************************
 * Copyright (c) 2025, 2026 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.watchdog;

import java.io.File;
import java.io.IOException;
import java.util.concurrent.TimeUnit;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SystemdWatchdogStrategy implements WatchdogStrategy {

    private static final Logger logger = LoggerFactory.getLogger(SystemdWatchdogStrategy.class);

    static final String NOTIFY_SOCKET_ENV = "NOTIFY_SOCKET";
    static final String WATCHDOG_USEC_ENV = "WATCHDOG_USEC";
    static final String WATCHDOG_PID_ENV = "WATCHDOG_PID";

    static final String SYSTEMD_NOTIFY_CMD = "systemd-notify";

    private static final String[] SYSTEMD_NOTIFY_PATHS = { "/usr/bin/systemd-notify", "/bin/systemd-notify" };

    private static final long SYSTEMD_NOTIFY_TIMEOUT_SEC = 5;

    private long watchdogUsec;
    private boolean degraded;
    private boolean suspended;
    private String pidArg;

    @Override
    public void activate(WatchdogServiceOptions options) throws Exception {
        String notifySocketPath = getEnvVar(NOTIFY_SOCKET_ENV);

        if (notifySocketPath == null || notifySocketPath.isEmpty()) {
            logger.warn(
                    "NOTIFY_SOCKET environment variable is not set. "
                            + "Running in degraded mode: systemd watchdog pings will not be sent. "
                            + "Ensure Kura is running as a systemd service with WatchdogSec= configured.");
            this.degraded = true;
            return;
        }

        if (!isSystemdNotifyAvailable()) {
            logger.warn(
                    "systemd-notify binary not found in standard locations ({}). "
                            + "Running in degraded mode: cannot send sd_notify watchdog pings. "
                            + "Install systemd-utils or switch watchdogMode to 'direct'.",
                    String.join(", ", SYSTEMD_NOTIFY_PATHS));
            this.degraded = true;
            return;
        }

        String watchdogPidStr = getEnvVar(WATCHDOG_PID_ENV);
        if (watchdogPidStr != null) {
            try {
                long expectedPid = Long.parseLong(watchdogPidStr);
                long currentPid = ProcessHandle.current().pid();
                if (expectedPid != currentPid) {
                    logger.debug(
                            "WATCHDOG_PID ({}) does not match current PID ({}). "
                                    + "This is expected for forking services. "
                                    + "systemd-notify will be used for watchdog pings.",
                            expectedPid, currentPid);
                }
            } catch (NumberFormatException e) {
                logger.debug("WATCHDOG_PID environment variable is not a valid number: '{}'. Ignoring.",
                        watchdogPidStr, e);
            }
        }

        String watchdogUsecStr = getEnvVar(WATCHDOG_USEC_ENV);
        if (watchdogUsecStr != null) {
            try {
                this.watchdogUsec = Long.parseLong(watchdogUsecStr);
                logger.info("systemd watchdog timeout set to {} usec ({} msec)", this.watchdogUsec,
                        this.watchdogUsec / 1000);
            } catch (NumberFormatException e) {
                logger.warn("WATCHDOG_USEC environment variable is not a valid number: '{}'. "
                        + "Watchdog timeout will not be available.", watchdogUsecStr, e);
            }
        }

        this.pidArg = "--pid=" + ProcessHandle.current().pid();

        logger.info("Systemd watchdog strategy activated. NOTIFY_SOCKET={}", notifySocketPath);
        this.degraded = false;
        this.suspended = false;
    }

    @Override
    public void refresh() {
        sendNotify("WATCHDOG=1");
    }

    @Override
    public void disable() {
        sendNotify("STOPPING=1");
        this.suspended = true;
    }

    @Override
    public void suspend() {
        this.suspended = true;
    }

    @Override
    public int getHardwareTimeout() {
        if (this.watchdogUsec > 0) {
            return (int) (this.watchdogUsec / 1000);
        }
        return 0;
    }

    @Override
    public void trigger() {
        sendNotify("WATCHDOG=trigger");
    }

    void notifyReady() {
        sendNotify("READY=1");
    }

    @Override
    public boolean isDegraded() {
        return this.degraded;
    }

    long getWatchdogUsec() {
        return this.watchdogUsec;
    }

    protected String getEnvVar(String name) {
        return System.getenv(name);
    }

    protected boolean isSystemdNotifyAvailable() {
        for (String path : SYSTEMD_NOTIFY_PATHS) {
            if (new File(path).exists()) {
                return true;
            }
        }
        return false;
    }

    // Each refresh() spawns a short-lived systemd-notify process. At the default
    // 10s ping interval this is ~8,640 spawns/day. While individually lightweight
    // with --no-block (~5ms each), this is not zero-cost. On heavily constrained
    // devices consider direct mode or increasing pingInterval. A future improvement
    // could use JNA to call sd_notify() directly, eliminating process overhead.
    private synchronized void sendNotify(String message) {
        if (this.degraded || this.suspended) {
            return;
        }

        try {
            Process proc = new ProcessBuilder(SYSTEMD_NOTIFY_CMD, "--no-block", this.pidArg, message).start();
            boolean finished = proc.waitFor(SYSTEMD_NOTIFY_TIMEOUT_SEC, TimeUnit.SECONDS);
            if (!finished) {
                proc.destroyForcibly();
                logger.warn("systemd-notify timed out for: {}", message);
            } else if (proc.exitValue() != 0) {
                logger.warn("systemd-notify failed with exit code {} for: {}", proc.exitValue(), message);
            } else {
                logger.debug("Sent notification: {}", message);
            }
            proc.getInputStream().close();
            proc.getErrorStream().close();
        } catch (IOException e) {
            logger.error("Failed to invoke systemd-notify for: {}", message, e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            logger.warn("systemd-notify interrupted for: {}", message);
        }
    }
}
