/*******************************************************************************
 * Copyright (c) 2011, 2026 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.watchdog;

import java.io.IOException;
import java.io.PrintWriter;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.TimeUnit;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.configuration.ConfigurableComponent;
import org.eclipse.kura.linux.watchdog.WatchdogServiceOptions.WatchdogMode;
import org.eclipse.kura.watchdog.CriticalComponent;
import org.eclipse.kura.watchdog.WatchdogService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class WatchdogServiceImpl implements WatchdogService, ConfigurableComponent {

    private static final Logger logger = LoggerFactory.getLogger(WatchdogServiceImpl.class);

    private static final long GRACE_PERIOD = Duration.ofMinutes(5).toNanos();

    private Long timedOutOn;
    private List<CriticalComponentRegistration> criticalComponentRegistrations;
    private ScheduledExecutorService pollExecutor;
    private ScheduledFuture<?> pollTask;
    private WatchdogServiceOptions options;
    private WatchdogStrategy watchdogStrategy;
    private WatchdogMode activeMode;

    protected void activate(Map<String, Object> properties) {
        this.criticalComponentRegistrations = new CopyOnWriteArrayList<>();
        this.pollExecutor = Executors.newSingleThreadScheduledExecutor();

        updated(properties);
    }

    protected void deactivate() {
        cancelPollTask();
        shutdownPollExecutor();
        if (this.watchdogStrategy != null) {
            this.watchdogStrategy.refresh();
            this.watchdogStrategy.disable();
        }
    }

    public void updated(Map<String, Object> properties) {
        WatchdogServiceOptions newOptions = new WatchdogServiceOptions(properties);

        if (this.pollTask != null && !this.pollTask.isCancelled()
                && this.options != null
                && this.activeMode == newOptions.getWatchdogMode()
                && this.options.isEnabled() == newOptions.isEnabled()
                && this.options.getPingInterval().equals(newOptions.getPingInterval())
                && this.options.getWatchdogDevice().equals(newOptions.getWatchdogDevice())
                && this.options.getRebootCauseFilePath().equals(newOptions.getRebootCauseFilePath())) {
            logger.info("Watchdog configuration unchanged. Keeping current strategy.");
            return;
        }

        this.pollExecutor.submit(() -> {
            Thread.currentThread().setName("WatchdogServiceImpl");
            cancelPollTask();
            if (this.watchdogStrategy != null) {
                this.watchdogStrategy.suspend();
            }
            doUpdate(newOptions);
        });
    }

    private void doUpdate(WatchdogServiceOptions newOptions) {
        boolean wasDisabled = this.options == null || !this.options.isEnabled();
        this.timedOutOn = null;
        this.options = newOptions;

        if (wasDisabled && newOptions.isEnabled()) {
            logger.info("Watchdog enabled. Resetting check-in times for {} critical component(s).",
                    this.criticalComponentRegistrations.size());
            for (CriticalComponentRegistration ccr : this.criticalComponentRegistrations) {
                ccr.update();
            }
        }

        WatchdogMode requestedMode = newOptions.getWatchdogMode();
        logger.info("Initializing watchdog strategy: {} (enabled={})", requestedMode.getValue(),
                newOptions.isEnabled());

        WatchdogMode activatedMode = activateStrategy(requestedMode, newOptions);

        if (activatedMode == null) {
            return;
        }

        if (activatedMode == WatchdogMode.DIRECT) {
            try (PrintWriter wdWriter = new PrintWriter(newOptions.getWatchdogEnabledTemporaryFilePath())) {
                wdWriter.write(newOptions.getWatchdogDevice());
            } catch (Exception e) {
                logger.warn("Unable to write watchdog enabled temporary file. Continuing anyway", e);
            }
        }

        this.activeMode = activatedMode;

        this.pollTask = this.pollExecutor.scheduleAtFixedRate(() -> {
            Thread.currentThread().setName("WatchdogServiceImpl");
            doTick();
        }, 0, this.options.getPingInterval(), TimeUnit.MILLISECONDS);
    }

    /**
     * Activates the requested watchdog strategy, falling back to the direct strategy when the requested one is
     * unavailable or degraded. Returns the mode that was actually activated, or {@code null} if no strategy could be
     * activated.
     */
    private WatchdogMode activateStrategy(WatchdogMode requestedMode, WatchdogServiceOptions newOptions) {
        for (WatchdogMode candidate : candidateModes(requestedMode)) {
            if (candidate != requestedMode) {
                logger.info("Falling back to {} watchdog strategy.", candidate.getValue());
            }
            WatchdogStrategy strategy = tryActivate(candidate, newOptions);
            if (strategy != null) {
                this.watchdogStrategy = strategy;
                return candidate;
            }
        }

        this.watchdogStrategy = null;
        return null;
    }

    private static List<WatchdogMode> candidateModes(WatchdogMode requestedMode) {
        if (requestedMode == WatchdogMode.DIRECT) {
            return List.of(WatchdogMode.DIRECT);
        }
        return List.of(requestedMode, WatchdogMode.DIRECT);
    }

    /**
     * Creates and activates a single watchdog strategy. Returns {@code null} if the strategy fails to activate or
     * reports degraded operation. The direct strategy opens (and thereby arms) the hardware watchdog device, so it is
     * activated only when the service is enabled; when disabled the device is left untouched.
     */
    private WatchdogStrategy tryActivate(WatchdogMode mode, WatchdogServiceOptions newOptions) {
        if (mode == WatchdogMode.DIRECT && !newOptions.isEnabled()) {
            logger.info("Watchdog is disabled; leaving the hardware watchdog device untouched (direct mode).");
            return null;
        }

        WatchdogStrategy strategy = createWatchdogStrategy(mode);
        try {
            strategy.activate(newOptions);
        } catch (Exception e) {
            logger.warn("Failed to activate watchdog strategy '{}'.", mode.getValue(), e);
            return null;
        }

        if (strategy.isDegraded()) {
            logger.warn("Watchdog strategy '{}' is running in degraded mode.", mode.getValue());
            return null;
        }

        return strategy;
    }

    private void doTick() {
        if (this.options != null && this.options.isEnabled()) {
            checkCriticalComponents();
        } else if (this.watchdogStrategy != null) {
            logger.debug("Refreshing watchdog (passive mode).");
            this.watchdogStrategy.refresh();
        }
    }

    protected WatchdogStrategy createWatchdogStrategy(WatchdogMode mode) {
        switch (mode) {
        case SYSTEMD:
            return new SystemdWatchdogStrategy();
        case DIRECT:
        default:
            return new DirectWatchdogStrategy();
        }
    }

    @Override
    @Deprecated
    public void startWatchdog() {
    }

    @Override
    @Deprecated
    public void stopWatchdog() {
    }

    @Override
    public int getHardwareTimeout() {
        if (this.watchdogStrategy != null) {
            return this.watchdogStrategy.getHardwareTimeout();
        }
        return 0;
    }

    @Override
    public void registerCriticalComponent(CriticalComponent criticalComponent) {
        boolean found = this.criticalComponentRegistrations.stream()
                .anyMatch(ccr -> ccr.getCriticalComponent() == criticalComponent);
        if (found) {
            logger.warn("Critical component '{}' already registered", criticalComponent.getCriticalComponentName());
            return;
        }
        CriticalComponentRegistration ccr = new CriticalComponentRegistration(criticalComponent);
        this.criticalComponentRegistrations.add(ccr);
    }

    @Override
    @Deprecated
    public void registerCriticalService(CriticalComponent criticalComponent) {
        registerCriticalComponent(criticalComponent);
    }

    @Override
    public void unregisterCriticalComponent(CriticalComponent criticalComponent) {
        this.criticalComponentRegistrations.removeIf(ccr -> ccr.getCriticalComponent() == criticalComponent);
    }

    @Override
    @Deprecated
    public void unregisterCriticalService(CriticalComponent criticalComponent) {
        unregisterCriticalComponent(criticalComponent);
    }

    @Override
    public List<CriticalComponent> getCriticalComponents() {
        List<CriticalComponent> result = new ArrayList<>();
        for (CriticalComponentRegistration ccr : this.criticalComponentRegistrations) {
            result.add(ccr.getCriticalComponent());
        }
        return Collections.unmodifiableList(result);
    }

    @Override
    public void checkin(CriticalComponent criticalComponent) {
        for (CriticalComponentRegistration ccr : this.criticalComponentRegistrations) {
            if (ccr.getCriticalComponent() == criticalComponent) {
                ccr.update();
                break;
            }
        }
    }

    protected void checkCriticalComponents() {
        logger.debug("Starting critical components check...");
        if (this.timedOutOn == null) {
            CriticalComponentRegistration ccr = getAnyTimedOutRegistration();
            if (ccr != null) {
                this.timedOutOn = System.nanoTime();
                logger.warn("Critical component '{}' timed out. System will reboot", ccr.getCriticalComponentName());

                RebootCauseFileWriter rebootCauseWriter = new RebootCauseFileWriter(
                        this.options.getRebootCauseFilePath());
                rebootCauseWriter.writeRebootCause(ccr.getCriticalComponentName());

                if (this.watchdogStrategy != null) {
                    this.watchdogStrategy.trigger();
                }

                try {
                    logger.debug("Requesting reboot.");
                    rebootSystem();
                } catch (KuraException e) {
                    logger.error("System reboot failed. Watchdog will not be refreshed", e);
                    this.timedOutOn -= GRACE_PERIOD;
                }
            }
        }

        if (this.timedOutOn == null || System.nanoTime() - this.timedOutOn < GRACE_PERIOD) {
            logger.debug("Refreshing watchdog.");
            if (this.watchdogStrategy != null) {
                this.watchdogStrategy.refresh();
            }
        }
    }

    private CriticalComponentRegistration getAnyTimedOutRegistration() {
        CriticalComponentRegistration result = null;

        for (CriticalComponentRegistration ccr : this.criticalComponentRegistrations) {
            if (ccr.isTimedOut()) {
                result = ccr;
                break;
            }
        }

        return result;
    }

    private synchronized void rebootSystem() throws KuraException {
        try {
            Process proc = Runtime.getRuntime().exec("sync");
            proc.waitFor();
        } catch (IOException e) {
            logger.error("Filesystem sync failed. Continuing", e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            logger.error("Filesystem sync interrupted. Continuing", e);
        }

        try {
            Process proc = Runtime.getRuntime().exec("reboot");
            int exitCode = proc.waitFor();
            if (exitCode != 0) {
                throw new KuraException(KuraErrorCode.OS_COMMAND_ERROR, "reboot", exitCode);
            }
        } catch (IOException e) {
            throw new KuraException(KuraErrorCode.PROCESS_EXECUTION_ERROR, e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new KuraException(KuraErrorCode.PROCESS_EXECUTION_ERROR, e);
        }
    }

    private void cancelPollTask() {
        if (this.pollTask != null && !this.pollTask.isCancelled()) {
            logger.debug("Cancelling watchdog task...");
            this.pollTask.cancel(false);
            logger.debug("Watchdog task cancelled? = {}", this.pollTask.isCancelled());
            this.pollTask = null;
        }
    }

    private void shutdownPollExecutor() {
        if (this.pollExecutor != null) {
            logger.debug("Terminating watchdog executor...");
            this.pollExecutor.shutdown();
            logger.debug("Watchdog executor terminated? - {}", this.pollExecutor.isTerminated());
            this.pollExecutor = null;
        }
    }
}
